local DadosLoja = {}

DadosLoja.MAX_SLOTS = 8
DadosLoja.TECLA_ABRIR = Enum.KeyCode.L
DadosLoja.Itens = {
	{
		Nome = "Poção de Velocidade",
		Descricao = "Poção de Velocidade\n+50% de velocidade",
		PrecoEsferas = 20,
		PrecoRobux = 10,
		Imagem = "rbxassetid://75203508047474",
	},
	{
		Nome = "Hamburger da Força",
		Descricao = "Hamburger da Força\n+50% de força quando chega em uma batalha",
		PrecoEsferas = 20,
		PrecoRobux = 18,
		Imagem = "rbxassetid://480036317",
	},
	{
		Nome = "Poção de Invisibilidade",
		Descricao = "Poção de Invisibilidade\nFica invisivel, 100% de invisibilidade",
		PrecoEsferas = 50,
		PrecoRobux = 30,
		Imagem = "rbxassetid://99340282332020",
	},
}

return DadosLoja
